### ISSUE TITLE
How many retrieved completions are prepended to the input?

### ISSUE THREAD

**Issue by wasiahmad** [microsoft/ReACC#2]
The second stage in ReACC is to complete codes based on the context and the retrieved codes. ReACC simply puts the retrieved code before the context and concat them as inputs. How many retrieve code are prepended? 

Does the choice depend on any predefined length? Let's say maximum allowed length is 1024 and the input is 256, then maximum length of the retrieved document could be 768. Because the completion sizes are less than 300, how the decision is made to consider the number of retrieved doc?

**Comment by celbree** [comment]
We always use a single retrieved doc, along with its following code snippet, as the input augmentation.
