### ISSUE TITLE
retriever训练

### ISSUE THREAD

**Issue by wanghanbinpanda** [microsoft/ReACC#5]
您好，请问：
1.如何获取针对于java的incomplete code-to-code retriever？，文中只提供了针对于python的retriever：[microsoft/reacc-py-retriever]，需要我们自己训练java的retriever吗？
2.如果我们想自己训练ReAcc framework中的retriever，应该如何获取数据集？是否需要我们自己找数据集，进行Transformation（Identifier renaming and Dead code insertion），然后进行训练，run  the codenet_test.py来评估我们的retriever？
谢谢！

**Comment by zoubaihan** [comment]
> 

您好，请问您最终找到或训练好java-retriever了吗？这个问题您最后是怎么解决的呢？

**Comment by wanghanbinpanda** [comment]
> > 
> 
> 您好，请问您最终找到或训练好java-retriever了吗？这个问题您最后是怎么解决的呢？

因公司政策原因，作者目前没有计划release Java的retriever，我目前还没有解决java-retriever，需自行获取代码预料训练
